workflow:
  rules:
    - if: $CI_COMMIT_TAG  # Create a pipeline if a tag is pushed
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Otherwise, create a pipeline if it's a push to the default branch

variables:
  # Use Docker-in-Docker service
  # More info: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlay2 driver
  DOCKER_DRIVER: overlay2
  # Override the clone URL to use the internal IP address via HTTPS
  # NOTE: This might fail if the certificate is not valid for the IP
  GIT_CLONE_URL: https://192.168.50.187/${CI_PROJECT_PATH}.git
  # Force a clean clone instead of fetch
  GIT_STRATEGY: clone

services:
  - docker:dind # Docker-in-Docker

stages:
  - build # Build stage for creating images

default:
  image: docker:latest # Use a standard docker image for the jobs
  tags:
    - k8s
  before_script:
    # $CI_REGISTRY_USER, $CI_REGISTRY_PASSWORD are predefined GitLab CI/CD variables
    # Explicitly log in to the target registry IP
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 192.168.50.187

build_medusa:
  stage: build
  script:
    - echo "<<<<< EXECUTING LATEST .gitlab-ci.yml - If you see this, the file is being read! >>>>>"
    - exit 1 # Intentionally fail the job here for testing
    - cd medusa
    - >
      docker build \\
        --tag "192.168.50.187/$CI_PROJECT_PATH/medusa:$CI_COMMIT_SHORT_SHA" \\
        --tag "192.168.50.187/$CI_PROJECT_PATH/medusa:latest" \\
        .
    - docker push "192.168.50.187/$CI_PROJECT_PATH/medusa:$CI_COMMIT_SHORT_SHA"
    - docker push "192.168.50.187/$CI_PROJECT_PATH/medusa:latest"
  # Job-level rules still apply, but only if a pipeline was created by the workflow
  rules:
    - if: $CI_COMMIT_TAG # Run for tags
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run for default branch
      changes:
        - medusa/**/*

build_storefront:
  stage: build
  script:
    - cd storefront
    - >
      docker build \\
        --build-arg NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=$NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY \\
        --build-arg NEXT_PUBLIC_SEARCH_API_KEY=$NEXT_PUBLIC_SEARCH_API_KEY \\
        --tag "192.168.50.187/$CI_PROJECT_PATH/storefront:$CI_COMMIT_SHORT_SHA" \\
        --tag "192.168.50.187/$CI_PROJECT_PATH/storefront:latest" \\
        .
    - docker push "192.168.50.187/$CI_PROJECT_PATH/storefront:$CI_COMMIT_SHORT_SHA"
    - docker push "192.168.50.187/$CI_PROJECT_PATH/storefront:latest"
  # Job-level rules still apply, but only if a pipeline was created by the workflow
  rules:
    - if: $CI_COMMIT_TAG # Run for tags
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run for default branch
      changes:
        - storefront/**/*