name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  packages: write # Needed to push images to GHCR

jobs:
  build_medusa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for medusa
        id: meta_medusa
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/medusa

      - name: Build and push Medusa image
        uses: docker/build-push-action@v6
        with:
          context: ./medusa
          push: true
          tags: ${{ steps.meta_medusa.outputs.tags }}
          labels: ${{ steps.meta_medusa.outputs.labels }}

  build_storefront:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for storefront
        id: meta_storefront
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/storefront

      - name: Build and push Storefront image
        uses: docker/build-push-action@v6
        with:
          context: ./storefront
          push: true
          tags: ${{ steps.meta_storefront.outputs.tags }}
          labels: ${{ steps.meta_storefront.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY }}
            NEXT_PUBLIC_SEARCH_API_KEY=${{ secrets.NEXT_PUBLIC_SEARCH_API_KEY }}
            NEXT_PUBLIC_MEDUSA_BACKEND_URL=${{ secrets.NEXT_PUBLIC_MEDUSA_BACKEND_URL }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_DEFAULT_REGION=${{ secrets.NEXT_PUBLIC_DEFAULT_REGION }}
            NEXT_PUBLIC_STRIPE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_KEY }} 